name: Release
on:
  push:
    branches: ['master', 'dev']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v5
        with:
          semantic_version: 24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
