name: Update Weekly Commit Stats

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every Monday at 08:00 UTC (11:00 Turkey time)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: weekly-commit-stats
  cancel-in-progress: false

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/commits/update-commit-stats.sh

      - name: Run stats update script
        run: ./scripts/commits/update-commit-stats.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: 'chore(docs): update weekly commit stats'
          branch: update/weekly-commit-stats
          title: 'chore(docs): update weekly commit stats'
          body: 'This PR updates the weekly commit stats.'
          base: master
