name: Update Weekly Commit Stats

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every Monday at 08:00 UTC (11:00 Turkey time)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: weekly-commit-stats
  cancel-in-progress: false

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/commit/update-commit-stats.sh

      - name: Run stats update script
        run: ./scripts/commit/update-commit-stats.sh

      - name: Commit and push changes if needed
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          if [[ -n "$(git status --porcelain .husky/README.md)" ]]; then
            git add .husky/README.md
            git commit -m "chore(docs): update weekly commit stats"
            git push origin "HEAD:${DEFAULT_BRANCH}"
          else
            echo "No changes to commit."
          fi
